spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/youtube
spring.datasource.username=postgres
spring.datasource.password=gatitas2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=isaprojekat112002@gmail.com
spring.mail.password=kaxnwrdmccaeausz
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true

# Frontend URL for activation links
app.frontend.url=http://localhost:4200

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Upload directories
app.upload.dir=videos
app.upload.thumbnail.dir=thumbnails

# Cache configuration
spring.cache.type=simple

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest